import { mkdirSync, writeFileSync } from "node:fs";
import { PNG } from "pngjs";
const sizes = [16, 32, 48, 64, 128, 256];
const outputDir = new URL("../build/", import.meta.url);
function setPixel(png, x, y, color) { if (x < 0 || y < 0 || x >= png.width || y >= png.height) return; const index = (png.width * y + x) << 2; png.data[index] = color[0]; png.data[index + 1] = color[1]; png.data[index + 2] = color[2]; png.data[index + 3] = color[3]; }
function ellipse(png, cx, cy, rx, ry, color) { const minX = Math.floor(cx - rx); const maxX = Math.ceil(cx + rx); const minY = Math.floor(cy - ry); const maxY = Math.ceil(cy + ry); for (let y = minY; y <= maxY; y += 1) for (let x = minX; x <= maxX; x += 1) { const dx = (x - cx) / rx; const dy = (y - cy) / ry; if (dx * dx + dy * dy <= 1) setPixel(png, x, y, color); } }
function polygon(png, points, color) { const minY = Math.floor(Math.min(...points.map((point) => point[1]))); const maxY = Math.ceil(Math.max(...points.map((point) => point[1]))); for (let y = minY; y <= maxY; y += 1) { const intersections = []; for (let index = 0; index < points.length; index += 1) { const start = points[index]; const end = points[(index + 1) % points.length]; if ((start[1] <= y && end[1] > y) || (end[1] <= y && start[1] > y)) intersections.push(start[0] + ((y - start[1]) * (end[0] - start[0])) / (end[1] - start[1])); } intersections.sort((left, right) => left - right); for (let index = 0; index + 1 < intersections.length; index += 2) for (let x = Math.ceil(intersections[index]); x <= intersections[index + 1]; x += 1) setPixel(png, x, y, color); } }
function createIcon(size) { const png = new PNG({ width: size, height: size }); const scale = size / 256; const p = (value) => value * scale; const navy = [24, 35, 55, 255]; const darker = [14, 23, 39, 255]; const white = [248, 251, 255, 255]; const orange = [244, 149, 54, 255]; ellipse(png, p(128), p(142), p(79), p(91), navy); ellipse(png, p(128), p(83), p(71), p(67), darker); ellipse(png, p(128), p(153), p(46), p(59), white); ellipse(png, p(101), p(77), p(14), p(18), white); ellipse(png, p(155), p(77), p(14), p(18), white); ellipse(png, p(104), p(80), p(5), p(8), darker); ellipse(png, p(152), p(80), p(5), p(8), darker); polygon(png, [[p(128), p(88)], [p(109), p(102)], [p(128), p(112)], [p(147), p(102)]], orange); ellipse(png, p(91), p(232), p(37), p(14), orange); ellipse(png, p(165), p(232), p(37), p(14), orange); return PNG.sync.write(png); }
function createIco(frames) { const header = Buffer.alloc(6); header.writeUInt16LE(0, 0); header.writeUInt16LE(1, 2); header.writeUInt16LE(frames.length, 4); const entries = Buffer.alloc(frames.length * 16); let offset = header.length + entries.length; frames.forEach(({ size, data }, index) => { const entry = index * 16; entries[entry] = size === 256 ? 0 : size; entries[entry + 1] = size === 256 ? 0 : size; entries.writeUInt16LE(1, entry + 4); entries.writeUInt16LE(32, entry + 6); entries.writeUInt32LE(data.length, entry + 8); entries.writeUInt32LE(offset, entry + 12); offset += data.length; }); return Buffer.concat([header, entries, ...frames.map((frame) => frame.data)]); }
mkdirSync(outputDir, { recursive: true }); const frames = sizes.map((size) => ({ size, data: createIcon(size) })); writeFileSync(new URL("penguin-icon.png", outputDir), frames.at(-1).data); writeFileSync(new URL("penguin-icon.ico", outputDir), createIco(frames));
